[project]
name = "markdown-mermaid"
version = "0.1"
authors = [
    { name = "rauaap" }
]
dependencies = [
    "markdown >= 3.4.1"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = 'https://github.com/rauaap/markdown-mermaid'
